/**
 * Frontend configuration module providing actor creation and network config.
 * This is the stable import target for '../config' usage throughout the app.
 */

import {
  Actor,
  type ActorConfig,
  type ActorSubclass,
  HttpAgent,
} from "@dfinity/agent";
import type { backendInterface } from "../backend";
import { getCanisterConfig } from "./canisters";

// Import idlFactory from the generated declarations
// This is typically generated by dfx generate
const _idlFactory = ({ IDL }: any) => {
  // This will be replaced by the actual generated idlFactory
  // For now, we'll dynamically import it
  return IDL.Service({});
};

export interface CreateActorOptions {
  agentOptions?: {
    identity?: any;
    host?: string;
  };
}

/**
 * Creates a backend actor with proper network and canister configuration.
 * Uses the centralized config resolver for consistent behavior across environments.
 */
export async function createActorWithConfig(
  options?: CreateActorOptions,
): Promise<backendInterface> {
  try {
    const config = getCanisterConfig();
    const host = options?.agentOptions?.host || config.network.host;

    const agent = new HttpAgent({
      host,
      identity: options?.agentOptions?.identity,
    });

    // Fetch root key only in local development
    if (config.network.isLocal) {
      await agent.fetchRootKey().catch((err) => {
        console.warn(
          "Unable to fetch root key. Check that the local replica is running.",
          err,
        );
      });
    }

    // Dynamically import the idlFactory from the generated backend module
    const backendModule = await import("../backend");
    const actualIdlFactory = (backendModule as any).idlFactory;

    if (!actualIdlFactory) {
      throw new Error(
        'idlFactory not found. Run "dfx generate backend" to generate canister declarations.',
      );
    }

    const actorConfig: ActorConfig = {
      agent,
      canisterId: config.backendCanisterId,
    };

    return Actor.createActor<backendInterface>(actualIdlFactory, actorConfig);
  } catch (error: any) {
    // Re-throw with context for better error handling upstream
    throw new Error(`Failed to create backend actor: ${error.message}`);
  }
}

// Re-export config utilities for convenience
export {
  getCanisterConfig,
  getNetworkConfig,
  getBackendCanisterId,
} from "./canisters";
