/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EncryptedKeyBytes = Uint8Array;
export interface EncryptedMessage {
  'id' : bigint,
  'to' : Principal,
  'from' : Principal,
  'messageType' : MessageType,
  'timestamp' : Time,
  'encryptedPayload' : Uint8Array,
  'encryptedSymmetricKey' : EncryptedKeyBytes,
}
export interface InviteCodeRecord {
  'code' : string,
  'used' : boolean,
}
export type MessageType = { 'iso20022' : null } |
  { 'swift' : null };
export interface SyncStatus {
  'otherHasPublicKey' : boolean,
  'callerHasPublicKey' : boolean,
  'isMutuallyTrusted' : boolean,
  'callerTrustsOther' : boolean,
  'otherTrustsCaller' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'publicKey' : [] | [Uint8Array],
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTrustedContact' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllMessagesForCaller' : ActorMethod<[], Array<EncryptedMessage>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactPublicKey' : ActorMethod<[Principal], [] | [Uint8Array]>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCodeRecord>>,
  'getMessageById' : ActorMethod<[bigint], EncryptedMessage>,
  'getRelationshipStatus' : ActorMethod<[Principal], SyncStatus>,
  'getTrustedContacts' : ActorMethod<[], Array<Principal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isTrustedContact' : ActorMethod<[Principal], boolean>,
  'removeTrustedContact' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<
    [Principal, MessageType, Uint8Array, EncryptedKeyBytes],
    bigint
  >,
  'submitInviteCode' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];