/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'publicKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'name' : IDL.Text,
});
export const MessageType = IDL.Variant({
  'iso20022' : IDL.Null,
  'swift' : IDL.Null,
});
export const Time = IDL.Int;
export const VetKeyBytes = IDL.Vec(IDL.Nat8);
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'from' : IDL.Principal,
  'messageType' : MessageType,
  'timestamp' : Time,
  'encryptedPayload' : IDL.Vec(IDL.Nat8),
  'keyId' : VetKeyBytes,
});
export const SyncStatus = IDL.Record({
  'otherHasPublicKey' : IDL.Bool,
  'callerHasPublicKey' : IDL.Bool,
  'isMutuallyTrusted' : IDL.Bool,
  'callerTrustsOther' : IDL.Bool,
  'otherTrustsCaller' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTrustedContact' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getRelationshipStatus' : IDL.Func([IDL.Principal], [SyncStatus], ['query']),
  'getTrustedContacts' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getUserMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isTrustedContact' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'removeTrustedContact' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func(
      [IDL.Principal, MessageType, IDL.Vec(IDL.Nat8), VetKeyBytes],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'publicKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'name' : IDL.Text,
  });
  const MessageType = IDL.Variant({
    'iso20022' : IDL.Null,
    'swift' : IDL.Null,
  });
  const Time = IDL.Int;
  const VetKeyBytes = IDL.Vec(IDL.Nat8);
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'from' : IDL.Principal,
    'messageType' : MessageType,
    'timestamp' : Time,
    'encryptedPayload' : IDL.Vec(IDL.Nat8),
    'keyId' : VetKeyBytes,
  });
  const SyncStatus = IDL.Record({
    'otherHasPublicKey' : IDL.Bool,
    'callerHasPublicKey' : IDL.Bool,
    'isMutuallyTrusted' : IDL.Bool,
    'callerTrustsOther' : IDL.Bool,
    'otherTrustsCaller' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTrustedContact' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getRelationshipStatus' : IDL.Func(
        [IDL.Principal],
        [SyncStatus],
        ['query'],
      ),
    'getTrustedContacts' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getUserMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isTrustedContact' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'removeTrustedContact' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func(
        [IDL.Principal, MessageType, IDL.Vec(IDL.Nat8), VetKeyBytes],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };