/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'id' : bigint,
  'to' : Principal,
  'from' : Principal,
  'messageType' : MessageType,
  'timestamp' : Time,
  'encryptedPayload' : Uint8Array,
  'keyId' : VetKeyBytes,
}
export type MessageType = { 'iso20022' : null } |
  { 'swift' : null };
export interface SyncStatus {
  'otherHasPublicKey' : boolean,
  'callerHasPublicKey' : boolean,
  'isMutuallyTrusted' : boolean,
  'callerTrustsOther' : boolean,
  'otherTrustsCaller' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'publicKey' : [] | [Uint8Array],
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VetKeyBytes = Uint8Array;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTrustedContact' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  /**
   * / Get the relationship status between the caller and ANY other user.
   * / This includes public key and trust relationship info.
   */
  'getRelationshipStatus' : ActorMethod<[Principal], SyncStatus>,
  'getTrustedContacts' : ActorMethod<[], Array<Principal>>,
  'getUserMessages' : ActorMethod<[Principal], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isTrustedContact' : ActorMethod<[Principal], boolean>,
  'removeTrustedContact' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<
    [Principal, MessageType, Uint8Array, VetKeyBytes],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];